# Generated by Django 2.0 on 2017-12-17 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='controle/images'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='unidades_pedidas',
            field=models.IntegerField(),
        ),
    ]
