# Generated by Django 2.0 on 2018-03-31 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0002_auto_20180331_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='unidades_no_estoque',
            new_name='unidades_compradas',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='unidades_pedidas',
        ),
    ]
