# Generated by Django 2.0 on 2018-05-20 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0003_auto_20180331_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemvendido',
            name='data_venda',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='itemvendido',
            name='desconto',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='itemvendido',
            name='preco_unitario',
            field=models.FloatField(),
        ),
    ]
