# Generated by Django 2.0 on 2018-02-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0003_cliente_itemvendido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemvendido',
            name='desconto',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
